import { Inter } from "next/font/google";
import "./globals.css";
//import { Courgette } from 'next/font/google';
//import { Rokkitt } from 'next/font/google';
//import { Oswald } from 'next/font/google';
import Header from "@/components/Header";
import Footer from "@/components/footer";
import Looder from "@/components/looder";
/*
const inter = Inter({ subsets: ["latin"] });
const courgette = Courgette({ 
  subsets: ['latin'],
  weight: ['400'],
  preload: false,
})

const oswald  = Oswald ({ 
  subsets: ['latin'],
  weight: ['300'],
  preload: false,
})
const rokkitt  = Rokkitt ({ 
  subsets: ['latin'],
  weight: ['400'],
  preload: false,
})

*/
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className="w-[100%] overflow-x-hidden flex justify-center flex-col items-center " >
     
         <Looder/>
        <div className={inter.className}>{children}
          <Footer />
        </div>
       
      </body>
     
    </html>
  );
}
